### ISSUE TITLE
Suggestion: list lammps package dependencies

### ISSUE THREAD

**Issue by matscalia** [lammpstutorials/lammpstutorials.github.io#80]
I'm walking through your tutorials on an Arch Linux machine and I have to rebuild lammps every time I discover a new package is needed after running the input. It's not that much of a deal but my machine is quite slow. I would suggest to list all packages needed by the full walkthrough and the specific packages needed by each tutorial before the introduction paragraph to let their independence unaffected.

If you don't have such handy list I will be happy to contribute once I get to the end.

As a side note, I love these tutorials, thanks!

**Comment by simongravelle** [comment]
Thank you very much for opening this issue. I am currently improving that particular part and hopefully the required packages and LAMMPS version will be listed soon.

**Comment by simongravelle** [comment]
Solved, see https://lammpstutorials.github.io/sphinx/build/html/non-tutorials/before-you-start.html

![Screenshot from 2023-12-09 21-31-43](https://github.com/lammpstutorials/lammpstutorials.github.io/assets/43388542/bf01b2e7-f0ff-4c4f-864a-d4fe8571621b)

**Comment by matscalia** [comment]
Awesome, thanks!
